project:
  type: website

website:
  title: Evaluating The Quality of Magic: the Gathering Cards for Drafting
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: model.qmd
        text: Model
      - href: creatures.qmd
        text: Creature Analysis
      - href: predictions.qmd
        text: Predictions
      - href: sources.qmd
        text: Sources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

