project:
  type: website

website:
  title: "Determining the Quality of Magic: the Gathering Cards for Drafting"
  navbar:
    left:
      - href: index.qmd
        text: Overview
      - href: model.qmd
        text: Model
      - href: creatures.qmd
        text: Creature Analysis
      - href: predictions.qmd
        text: Predictions
      - href: sources.qmd
        text: Sources
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

editor: visual

